openapi: 3.0.0
info:
  title: Auth API
  version: 1.0.0
  description: Authentication endpoints (register, login, logout, token refresh, OTP verification, phone verification)

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        email:
          type: string
          format: email
        phoneNumber:
          type: string
        emailVerified:
          type: boolean
        phoneVerified:
          type: boolean
        refreshToken:
          type: string
        TOSAccepted:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
          nullable: true

    RegisterRequest:
      type: object
      required: [firstname, lastname, email, TOSAccepted]
      properties:
        firstname:
          type: string
        lastname:
          type: string
        email:
          type: string
          format: email
        TOSAccepted:
          type: boolean

    LoginRequest:
      type: object
      required: [email]
      properties:
        email:
          type: string
          format: email

    LoginResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
        accessToken:
          type: string
        refreshToken:
          type: string

    VerifyOTPRequest:
      type: object
      required: [email, otpCode]
      properties:
        email:
          type: string
          format: email
          description: The user's email address.
        otpCode:
          type: string
          description: The 6-digit code sent to the user's email.
        rememberMe:
          type: boolean
          description: If true, the refresh token will have a longer expiration.
          default: false

    RefreshTokenRequest:
      type: object
      properties:
        refreshToken:
          type: string

    LogoutRequest:
      type: object
      properties:
        refreshToken:
          type: string

    VerifyRequest:
      type: object
      properties:
        token:
          type: string

paths:
  /auth/register:
    post:
      tags: [Auth]
      summary: Start user registration with OTP
      description: Creates a new user record and sends a one-time password (OTP) to their email to start the verification process.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User created and OTP sent. The user object is returned.
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
        '400':
          description: Validation error or email already in use

  /auth/login:
    post:
      tags: [Auth]
      summary: Start user login with OTP
      description: Sends a one-time password (OTP) to the user's email to start the login process.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: OTP sent successfully. The user object is returned.
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
        '401':
          description: User not found

  /auth/verify-otp:
    post:
      tags: [Auth]
      summary: Verify OTP and complete login/registration
      description: Verifies the OTP for the given email and, if successful, logs the user in by returning access and refresh tokens.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyOTPRequest'
      responses:
        '200':
          description: OTP verified and logged in successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Invalid or expired OTP.

  /auth/logout:
    post:
      tags: [Auth]
      summary: Logout user (invalidate refresh token)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogoutRequest'
      responses:
        '204':
          description: Logged out (cookie cleared)

  /auth/refresh-token:
    post:
      tags: [Auth]
      summary: Refresh access token using a refresh token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
      responses:
        '200':
          description: New tokens issued
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  refreshToken:
                    type: string
        '401':
          description: Invalid or expired refresh token

  /auth/verify-phone-number:
    post:
      tags: [Auth]
      summary: Verify user phone number using token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyRequest'
      responses:
        '204':
          description: Phone number verified
