openapi: 3.0.0
info:
  title: Salon API
  version: 1.0.0
  description: Salon related endpoints (create, update, list, get by organisation, get by id, delete)

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Salon:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        organisationId:
          type: string
        location:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
          nullable: true

    CreateSalonRequest:
      type: object
      required: [organisationId, name, location]
      properties:
        organisationId:
          type: string
        name:
          type: string
        location:
          type: string

    UpdateSalonRequest:
      type: object
      properties:
        name:
          type: string
        organisationId:
          type: string
        location:
          type: string
        createdAt:
          type: string
          format: date-time

paths:
  /salons:
    post:
      tags: [Salon]
      summary: Create a new salon
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSalonRequest'
      responses:
        '201':
          description: Salon created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Salon'
        '400':
          description: Validation error or missing fields
        '401':
          description: Unauthorized

    get:
      tags: [Salon]
      summary: Get all salons
      responses:
        '200':
          description: List of salons
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Salon'
        '500':
          description: Server error

  /salons/organisation/{organisationId}:
    get:
      tags: [Salon]
      summary: Get salons by organisation id
      parameters:
        - in: path
          name: organisationId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of salons for the organisation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Salon'
        '404':
          description: Organisation not found or no salons

  /salons/{id}:
    get:
      tags: [Salon]
      summary: Get salon by id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Salon found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Salon'
        '404':
          description: Salon not found

    post:
      tags: [Salon]
      summary: Update a salon (uses POST for updates)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSalonRequest'
      responses:
        '200':
          description: Updated salon
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Salon'
        '400':
          description: Validation error
        '401':
          description: Unauthorized
        '404':
          description: Salon not found

  /salons/{id}/delete:
    post:
      tags: [Salon]
      summary: Delete a salon (uses POST for delete)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Salon deleted (no content)
        '401':
          description: Unauthorized
        '404':
          description: Salon not found

tags:
  - name: Salon
    description: Salon management endpoints

