openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
  description: Endpoints for user management, staff scheduling, appointments and staff procedures

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        username:
          type: string
        email:
          type: string
          format: email
        phoneNumber:
          type: string
          nullable: true
        emailVerified:
          type: boolean
        phoneVerified:
          type: boolean
        refreshToken:
          type: string
        TOSAccepted:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
          nullable: true

    StaffOptions:
      type: object
      properties:
        availableForAppointments:
          type: boolean
        availableWeekDays:
          type: array
          items:
            type: string
        availableHours:
          type: array
          items:
            type: string
        nonAvailableRange:
          type: array
          items:
            type: string

    CreateAssignRequest:
      type: object
      required: [userData, salonId, roleId]
      properties:
        userData:
          type: object
          properties:
            firstname:
              type: string
            lastname:
              type: string
            username:
              type: string
            email:
              type: string
              format: email
            password:
              type: string
            phoneNumber:
              type: string
        salonId:
          type: string
        roleId:
          type: string
        staffOptions:
          $ref: '#/components/schemas/StaffOptions'

    AssignRequest:
      type: object
      required: [userId, salonId, roleId]
      properties:
        userId:
          type: string
        salonId:
          type: string
        roleId:
          type: string
        staffOptions:
          $ref: '#/components/schemas/StaffOptions'

    AssignRoleRequest:
      type: object
      required: [userId, roleId]
      properties:
        userId:
          type: string
          description: The ID of the user to whom the role will be assigned.
        roleId:
          type: string
          description: The ID of the role to be assigned.
        organisationId:
          type: string
          description: Optional. The ID of the organisation for context.
          nullable: true
        salonId:
          type: string
          description: Optional. The ID of the salon for context.
          nullable: true

    SetWorkingScheduleRequest:
      type: object
      required: [availableWeekDays, availableHours]
      properties:
        availableWeekDays:
          type: array
          items:
            type: string
        availableHours:
          type: array
          items:
            type: string

    SetAvailabilityRequest:
      type: object
      required: [available]
      properties:
        available:
          type: boolean

    NonAvailableRangeRequest:
      type: object
      required: [start, end, reason]
      properties:
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
        reason:
          type: string

    StaffPerformedProcedureRequest:
      type: object
      required: [staffId, procedureId, durationMinutes, price]
      properties:
        staffId:
          type: string
        procedureId:
          type: string
        durationMinutes:
          type: integer
          format: int32
        price:
          type: string

    Procedure:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        durationMinutes:
          type: integer
        price:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
          nullable: true

    StaffProceduresResponseItem:
      type: object
      properties:
        staffId:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        procedures:
          type: array
          items:
            $ref: '#/components/schemas/Procedure'

    BookAppointmentRequest:
      type: object
      required: [staffId, procedureIds, appointmentDate]
      properties:
        clientId:
          type: string
          description: Optional; if omitted, authenticated user's id is used
        staffId:
          type: string
        procedureIds:
          type: array
          items:
            type: string
        appointmentDate:
          type: string
          format: date-time

    CompleteAppointmentRequest:
      type: object
      required: [staffId]
      properties:
        staffId:
          type: string

    RequestCancelRequest:
      type: object
      required: [userId, reason]
      properties:
        userId:
          type: string
        reason:
          type: string

    UpdateUserRequest:
      type: object
      properties:
        firstname:
          type: string
        lastname:
          type: string
        email:
          type: string
          format: email
        phoneNumber:
          type: string

    CreateUserRequest:
      type: object
      required: [firstname, lastname, email]
      properties:
        firstname:
          type: string
        lastname:
          type: string
        email:
          type: string
          format: email
        phoneNumber:
          type: string
          nullable: true

paths:
  /users:
    post:
      tags: [User]
      summary: Create a new user
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: Created user object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Missing required fields
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    get:
      tags: [User]
      summary: Get all users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

  /users/{id}:
    get:
      tags: [User]
      summary: Get a user by ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: User not found
    post:
      tags: [User]
      summary: Update a user by ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        '200':
          description: Updated user object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: User not found

  /users/{id}/delete:
    post:
      tags: [User]
      summary: Delete a user by ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: User deleted successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: User not found

  /users/create-assign:
    post:
      tags: [User]
      summary: Create a new user and assign to a salon as staff
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAssignRequest'
      responses:
        '201':
          description: Created user object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Validation or missing data
        '401':
          description: Unauthorized

  /users/assign:
    post:
      tags: [User]
      summary: Assign an existing user to a salon as staff
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssignRequest'
      responses:
        '204':
          description: Assigned successfully (no content)
        '400':
          description: Validation error
        '401':
          description: Unauthorized
        '404':
          description: User, salon or role not found

  /users/assign-role:
    post:
      tags: [User]
      summary: Assign a role to a user
      description: Assigns a role to a user within an optional organisation or salon context. This also assigns all permissions associated with the role to the user.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssignRoleRequest'
      responses:
        '204':
          description: Role assigned successfully (no content).
        '400':
          description: Validation error.
        '401':
          description: Unauthorized.
        '403':
          description: Forbidden.
        '404':
          description: User or role not found.

  /users/{salonId}/schedule:
    post:
      tags: [User]
      summary: Set authenticated staff user's working schedule for a salon
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: salonId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetWorkingScheduleRequest'
      responses:
        '204':
          description: Schedule updated
        '401':
          description: Unauthorized
        '404':
          description: SalonStaff relation not found

  /users/{salonId}/availability:
    post:
      tags: [User]
      summary: Set authenticated staff user's availability for appointments in a salon
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: salonId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetAvailabilityRequest'
      responses:
        '204':
          description: Availability updated
        '401':
          description: Unauthorized
        '404':
          description: SalonStaff relation not found

  /users/{salonId}/non-available:
    post:
      tags: [User]
      summary: Add a non-available range for authenticated staff user (cancels appointments in range)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: salonId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NonAvailableRangeRequest'
      responses:
        '204':
          description: Non-available range set and affected appointments canceled
        '400':
          description: Invalid date range
        '401':
          description: Unauthorized
        '404':
          description: SalonStaff relation not found

  /users/staff/procedure:
    post:
      tags: [User]
      summary: Add a performed procedure record for a staff
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StaffPerformedProcedureRequest'
      responses:
        '201':
          description: Procedure recorded
        '400':
          description: Validation error
        '401':
          description: Unauthorized
        '404':
          description: Staff or procedure not found

  /users/salon/{salonId}/staff-procedures:
    get:
      tags: [User]
      summary: Get staff members in a salon and their performed procedures
      parameters:
        - in: path
          name: salonId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of staff with their procedures
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StaffProceduresResponseItem'
        '404':
          description: Salon not found or no staff

  /users/book:
    post:
      tags: [User]
      summary: Book an appointment with a staff
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookAppointmentRequest'
      responses:
        '201':
          description: Appointment created
        '400':
          description: Validation error or invalid date
        '401':
          description: Unauthorized
        '404':
          description: Client or staff not found

  /users/appointment/{appointmentId}/complete:
    post:
      tags: [User]
      summary: Mark an appointment as completed (staff only)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: appointmentId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompleteAppointmentRequest'
      responses:
        '200':
          description: Appointment marked as completed
        '401':
          description: Unauthorized
        '403':
          description: Not authorized to complete this appointment
        '404':
          description: Appointment not found

  /users/appointment/{appointmentId}/request-cancel:
    post:
      tags: [User]
      summary: Request appointment cancellation by user (sends email to staff)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: appointmentId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestCancelRequest'
      responses:
        '200':
          description: Cancellation request sent to staff
        '400':
          description: Validation error
        '401':
          description: Unauthorized
        '403':
          description: Not authorized to request cancellation for this appointment
        '404':
          description: Appointment or staff email not found

  /users/organisation/{organisationId}:
    get:
      tags:
        - User
      summary: Get all users in an organisation
      description: Retrieves a list of all users belonging to a specific organisation, including their salon and role information.
      parameters:
        - name: organisationId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The ID of the organisation.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of users in the organisation.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    user:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        firstname:
                          type: string
                        lastname:
                          type: string
                        email:
                          type: string
                          format: email
                    salon:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        name:
                          type: string
                    roles:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                            format: uuid
                          name:
                            type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Organisation not found

tags:
  - name: User
    description: User, staff and appointment related endpoints
